### ISSUE TITLE
How to access the path of a 2D texture of a PLY

### ISSUE THREAD

**Issue by Bjerken** [keijiro/PcxEffects3#1]
Hi!
I am trying to access the path of the Position map and Color maps (The 2D textures) of a PLY. I can only seem to access the path of the PLY itself. Though it is possible to access the 2D textures through the graph editor. Do you have any solution?

**Comment by keijiro** [comment]
You're referring a wrong repository. This repository only provides a VFX example.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen it for further problems.
