### ISSUE TITLE
error CS0246: The type or namespace name 'RaycastHit2D' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by penutbutter1111** [keijiro/PcxEffects3#2]
Hi, can you help resolve this? When I import XR-plugin management package to use this effect in VR I get the following errors:

Library\PackageCache\com.unity.xr.interaction.toolkit@0.10.0-preview.7\Runtime\UI\TrackedDeviceGraphicRaycaster.cs(128,44): error CS0246: The type or namespace name 'RaycastHit2D' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.unity.xr.interaction.toolkit@0.10.0-preview.7\Runtime\UI\TrackedDeviceGraphicRaycaster.cs(128,16): error CS0246: The type or namespace name 'RaycastHit2D' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.unity.xr.interaction.toolkit@0.10.0-preview.7\Runtime\UI\TrackedDeviceGraphicRaycaster.cs(101,18): error CS0246: The type or namespace name 'RaycastHit2D' could not be found (are you missing a using directive or an assembly reference?)

Thank you.

**Comment by keijiro** [comment]
I think you removed the built-in physics package using the Package Manager. Revert it to avoid this error message.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
